const config = {
  menu: [{
    text: '首页',
    url: '/home',
    icon: 'icon-home'
  }, {
    text: '用户管理',
    url: '/users',
    icon: 'icon-users'
  }, {
    text: '项目管理',
    url: '/projects',
    icon: 'icon-projects'
  }, {
    text: '文章管理',
    url: '/articles',
    icon: 'icon-articles'
  }, {
    text: '图库管理',
    url: '/photos',
    icon: 'icon-photos'
  }, {
    text: '权限管理',
    url: '/manage',
    icon: 'icon-manage'
  }, {
    text: '统计',
    url: '/count',
    icon: 'icon-count'
  }, {
    text: '日程',
    url: '/daily',
    icon: 'icon-daily'
  }, {
    text: '设置',
    url: '/setting',
    icon: 'icon-setting'
  }, {
    text: '关于',
    url: '/about',
    icon: 'icon-about'
  }],
  caption: [
    '序号',
    '数据库显示名称',
    '数据库名称',
    '默认数据库',
    '数据库类型',
    '服务器地址',
    '端口号',
    '数据库描述',
    '操作'
  ],
  info: [{
    tit: '信息中心数据库',
    entit: 'XXZXSJK',
    default: 'XXZXSJK',
    type: 'PostgreSQL',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库1',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库2',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'MySQL',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库3',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库4',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库5',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库6',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库7',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库8',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库9',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库10',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库11',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库12',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库13',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库14',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库15',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库16',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库17',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库18',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库19',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库20',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Oracle',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库21',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'Hive',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }, {
    tit: '卫人委数据库22',
    entit: 'WRWSJL',
    default: 'WRWSJL',
    type: 'SQLServer',
    ip: '10.0.0.14',
    post: 54320,
    description: '数据采集库'
  }]
}
export default config
